### ISSUE TITLE
Electrified doors don't shock anymore.

### ISSUE THREAD

**Issue by Carbonhell** [HippieStationArchive/HippieStation13-1#508]
As the title says, if you hack a door or run into an electrified doors, the sparks appear but you don't get stunned nor harmed, therefore any kind of insulated gloves is now useless.

**Comment by whitefox08** [comment]
![xkxb9q5](https://cloud.githubusercontent.com/assets/2702850/9660205/0b658124-521a-11e5-8fcc-39e6aad1ea5a.jpg)
![ft4wr6y](https://cloud.githubusercontent.com/assets/2702850/9660204/0b610da6-521a-11e5-82a9-2085af829ac8.jpg)

Works both for hacking and AI electrified. Are you sure the door had power?

**Comment by WhiteFox08** [comment]
Fixed in #523

**Comment by WhiteFox08** [comment]
Issue is still present relooking into this.

**Comment by AliiTea** [comment]
You don't get shocked from anything.. not just doors

**Comment by ghost** [comment]
rofl 10/10 coding

**Comment by nalarmg** [comment]
You still get shocked by wires if you attack them with objects.

**Comment by Jaygriff** [comment]
Yep, shocking by hitting on wires still works.

**Comment by Chronitonity** [comment]
APCs and Grilles still shock too
